# -*- coding: utf-8 -*-

import os

for j in range(1, 25):
    np = str(j)
    if not os.path.exists(np):
        os.mkdir(np)
    if not os.path.isfile(str(j)+'\\test'+str(j)+'.txt'):
        with open(str(j)+'\\test'+str(j)+'.txt', 'w') as f:
            f.write('')
    if not os.path.isfile(str(j)+'\\input'+str(j)+'.txt'):
        with open(str(j)+'\\input'+str(j)+'.txt', 'w') as f:
            f.write('')
    ldCode = '''
# --------------------------
# This code is autogenerated
data = 0
while data not in [1, 2]:
    data = int(input('Which data set do you want to use? 1 = Test, 2 = Input '))
if data == 1:
    fn = 'test'+str({i})+'.txt'
elif data == 2:
    fn = 'input'+str({i})+'.txt'
f = open(fn, 'r')
raw = [j for j in f.read().splitlines()]
# --------------------------
    '''.format(i=str(j))
    with open(str(j)+'\\code'+str(j)+'.py', 'w') as f:
        f.write(ldCode)